# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a84b4b60c771a5b1a33f3cbfb45f68c9870309556af44f3c01ca67f115db3abcd46d87e1dcc3c48f1895d460bcc659d1401347f7b5189c0b25e575a56127d85c

test:
  secret_key_base: e8238003e3a32773f3d0e7085c779af2494a5ad8088da9b8c23305b697c05b228ab37f7c74ebcf09e3bde80803f723afe6e4b46594ae8225c7411e1cef140f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
